var SlideDeck;var SlideDeckSkin={};var SlideDeckLens={};var flagSpineShowAlways=!1;var slideDeckImagesLoaded=!1;var CTAfunction=function(url)
{window.open(url,'_blank')}
jQuery(window).load(function(e){var slidedecks=jQuery('.slidedeck-frame .slidedeck').slidedeck();if(slideDeckImagesLoaded===!0){slideckAutoAdjustImagesOnLoad(slidedecks)}
else{if((jQuery('dd img.sd2-is-first-slide')))
{jQuery('.slidedeck-frame .slidedeck .sd2-content-wrapper').show()}
jQuery(window).on('slidedeckImagesLoaded',function(){slideckAutoAdjustImagesOnLoad(slidedecks)})}
if(typeof slidedecks!=="undefined")
{var $slides=jQuery(slidedecks.slides);if($slides.closest('lens-parfocal')){$slides.find('img').css('visibility','visible')}}});function slideckAutoAdjustImagesOnLoad(slidedecks)
{if(typeof slidedecks!=="undefined")
{for(var i=0;i<slidedecks.length;i++){slidedecks[i].autoAdjustAfterLoad()}
if(typeof slidedecks.length==="undefined"){slidedecks.autoAdjustAfterLoad()}}
jQuery('.slidedeck-frame .slidedeck .sd2-content-wrapper').show()}
function addEvent(evnt,elem,func){if(elem.addEventListener)
elem.addEventListener(evnt,func,!1);else if(elem.attachEvent){elem.attachEvent("on"+evnt,func)}
else{elem[evnt]=func}}
jQuery(document).ready(function(e){jQuery('img.slide-deck-lazy').jail({timeout:500,loadHiddenImages:!0,loadAllHorizontal:!0,callback:function(){slideDeckImagesLoaded=!0;jQuery(window).trigger('slidedeckImagesLoaded')},});var supportsOrientationChange="onorientationchange" in window,orientationEvent=supportsOrientationChange?"orientationchange":"resize";addEvent(orientationEvent,window,function(){var slidedecks=jQuery('.slidedeck-frame .slidedeck').slidedeck();if(typeof slidedecks!=="undefined"){for(var i=0;i<slidedecks.length;i++){slidedecks[i].reloadSlidedeck()}
if(typeof slidedecks.length==="undefined"){slidedecks.reloadSlidedeck()}}});jQuery(".lens-classic dl").hover(function(e){jQuery("dt.spine").stop(!0,!0).fadeIn()},function(e){if(jQuery(this).parent().is('.display-nav-hover'))
{jQuery("dt.spine").stop(!0,!0).fadeOut()}})});(function($){window.SlideDeck=function(el,opts){var self=this,el=$(el),versionPrefix='',distribution='pro';if(typeof(window.slideDeck2Version)!=='undefined'){versionPrefix='sd2-'+window.slideDeck2Version+'-'}
if(typeof(window.slideDeck2Distribution)!=='undefined'){distribution=window.slideDeck2Distribution}
var VERSION=versionPrefix+"1.4.4";var device_width=screen.width;this.options={speed:500,transition:'swing',start:1,activeCorner:!0,index:!0,scroll:!0,keys:!0,autoPlay:!1,autoPlayInterval:5000,hideSpines:!1,cycle:!1,slideTransition:'slide',touchThreshold:{x:50,y:30},touch:!0,controlProgress:!1,auto_height:!1,device_width:device_width,fashion:!1};this.classes={slide:'slide',spine:'spine',label:'label',index:'index',active:'active',indicator:'indicator',activeCorner:'activeCorner',disabled:'disabled',vertical:'slidesVertical',previous:'previous',next:'next'};this.current=1;this.deck=el;this.former=-1;this.spines=el.children('dt');if(typeof opts!=="undefined"&&opts.fashion)
this.slides=el.children('li');else this.slides=el.children('dd');if(el.children('li').length>0){this.options.cycle=!0;this.slides=el.children('li')}
this.controlTo=1;this.session=[];this.disabledSlides=[];this.pauseAutoPlay=!1;this.isLoaded=!1;var UA=navigator.userAgent.toLowerCase();this.browser={chrome:UA.match(/chrome/)?!0:!1,chromeFrame:(UA.match(/msie/)&&UA.match(/chrome/))?!0:!1,chromeiOS:UA.match(/crios/)?!0:!1,firefox:UA.match(/firefox/)?!0:!1,firefox2:UA.match(/firefox\/2\./)?!0:!1,firefox30:UA.match(/firefox\/3\.0/)?!0:!1,msie:UA.match(/msie/)?!0:!1,msie6:(UA.match(/msie 6/)&&!UA.match(/msie 7|8/))?!0:!1,msie7:UA.match(/msie 7/)?!0:!1,msie8:UA.match(/msie 8/)?!0:!1,msie9:UA.match(/msie 9/)?!0:!1,msie10:UA.match(/msie 10/)?!0:!1,opera:UA.match(/opera/)?!0:!1,safari:(UA.match(/safari/)&&!UA.match(/chrome|crios/))?!0:!1};for(var b in this.browser){if(this.browser[b]===!0){this.browser._this=b}}
if(this.browser.chrome===!0&&!this.browser.chromeFrame){this.browser.version=UA.match(/chrome\/([0-9\.]+)/)[1]}
if(this.browser.firefox===!0){this.browser.version=UA.match(/firefox\/([0-9\.]+)/)[1]}
if(this.browser.msie===!0){this.browser.version=UA.match(/msie ([0-9\.]+)/)[1]}
if(this.browser.opera===!0){this.browser.version=UA.match(/version\/([0-9\.]+)/)[1]}
if(this.browser.safari===!0&&!this.browser.chromeiOS){this.browser.version=UA.match(/version\/([0-9\.]+)/)[1]}
if(this.browser.chromeiOS===!0){this.browser.version=UA.match(/crios\/([0-9\.]+)/)[1]}
var width;var height;var spine_inner_width,spine_outer_width,slide_width,spine_half_width;this.looping=!1;var prefix="";switch(self.browser._this){case "firefox":case "firefox3":prefix="-moz-";break;case "chrome":case "safari":prefix="-webkit-";break;case "opera":prefix="-o-";break}
var FixIEAA=function(spine){if(self.browser.msie&&(!self.browser.msie9&&!self.browser.msie10)){var bgColor=spine.css('background-color');var sBgColor=bgColor;if(sBgColor==="transparent"){bgColor="#ffffff"}else{if(sBgColor.match('#')){if(sBgColor.length<7){var t="#"+sBgColor.substr(1,1)+sBgColor.substr(1,1)+sBgColor.substr(2,1)+sBgColor.substr(2,1)+sBgColor.substr(3,1)+sBgColor.substr(3,1);bgColor=t}}}
bgColor=bgColor.replace("#","");var cParts={r:bgColor.substr(0,2),g:bgColor.substr(2,2),b:bgColor.substr(4,2)};var bgRGB="#";var hexVal="01234567890ABCDEF";for(var k in cParts){cParts[k]=Math.max(0,(parseInt(cParts[k],16)-1));cParts[k]=hexVal.charAt((cParts[k]-cParts[k]%16)/16)+hexVal.charAt(cParts[k]%16);bgRGB+=cParts[k]}
spine.find('.'+self.classes.index).css({'filter':'progid:DXImageTransform.Microsoft.BasicImage(rotation=1) chroma(color='+bgRGB+')',backgroundColor:bgRGB})}};var slidedeckAdjustImage=function(slide){if(!$(slide).closest(".lens-pixel").length){if($(window).width()<400&&window.self!==window.top)return;}var isIE=($('.slidedeck-frame').hasClass('msie-8'))?!0:!1;$(slide).find('img').css('visibility','visible');if(!$(slide).closest(".lens-prime").length&&!$(slide).closest(".lens-parfocal").length&&!$(slide).closest(".lens-parallax").length&&!$(slide).closest(".lens-layerpro").length){jQuery(slide).ready(function(){var th=$(slide).height(),tw=$(slide).outerWidth(),im=$(slide).children('img.sd2-slide-background');if(im.length>0){var ih=im[0].naturalHeight,iw=im[0].naturalWidth;if(jQuery(slide).hasClass('sd2-image-scaling-none')){if(!isIE)return;im.css({maxWidth:'none'});var hd=(ih-th)/2,wd=(iw-tw)/2;if(ih>th){im.css({marginTop:'-'+hd+'px'})}else if(ih<th){im.css({marginTop:Math.abs(hd)+'px'})}
if(iw>tw){im.css({marginLeft:'-'+wd+'px'})}else{im.css({marginLeft:'auto'});im.css({marginRight:'auto'})}}else if(jQuery(slide).hasClass('sd2-image-scaling-contain')){var xh=parseInt((im.width()/im.height())*th+8);if(!(jQuery(slide).parent().parent().is(".display-nav-always"))||!(jQuery(slide).parent().parent().is(".lens-classic"))){jQuery(slide).find('img.sd2-slide-background').css({"margin":"0 auto","width":+xh+"px"})}else if(jQuery(slide).parent().parent().is(".display-nav-always")&&jQuery(slide).parent().parent().is(".lens-classic")){jQuery(slide).find('img.sd2-slide-background').css({"width":+xh+"px"})}
if(!isIE)return;im.addClass('slidedeck-adjust-height').removeClass('slidedeck-adjust-width');var nh=im.height(),nw=im.width(),hd=(nh-th)/2,wd=(nw-tw)/2;if(nw>tw){im.addClass('slidedeck-adjust-width').removeClass('slidedeck-adjust-height');var nh=im.height(),nw=im.width(),hd=(nh-th)/2,wd=(nw-tw)/2;if(nh>th){im.css({marginTop:'-'+hd+'px'})}else if(nh<th){im.css({marginTop:Math.abs(hd)+'px'})}}else{im.css({marginLeft:'auto'});im.css({marginRight:'auto'})}}else if(jQuery(slide).hasClass('sd2-image-scaling-cover')){if(ih>iw){im.addClass('slidedeck-adjust-width').removeClass('slidedeck-adjust-height')}else{im.addClass('slidedeck-adjust-height').removeClass('slidedeck-adjust-width')}
var nh=im.height(),nw=im.width(),hd=(nh-th)/2,wd=(nw-tw)/2;if(nh>th){im.css({marginTop:'-'+hd+'px'})}else if(nh<th){im.css({marginTop:Math.abs(hd)+'px'})}
if(nw>=tw){im.css({marginLeft:'-'+wd+'px'})}else{im.addClass('slidedeck-adjust-width').removeClass('slidedeck-adjust-height');var nh=im.height(),nw=im.width(),hd=(nh-th)/2,wd=(nw-tw)/2;if(nh>th){if(!im.closest(".sd2-fullwidth")){im.css({marginTop:'-'+hd+'px'})}}}}}})}}
var updateAddons=function(){if(typeof(Cufon)!=="undefined"){Cufon.DOM.ready(function(){if(typeof(self.options.cufonRefresh)!=="undefined"){var cufon_arr=[];if(typeof(self.options.cufonRefresh)==="string"){cufon_arr.push(self.options.cufonRefresh)}else{cufon_arr=self.options.cufonRefresh}
for(var i=0;i<cufon_arr.length;i++){Cufon.refresh(cufon_arr[i])}}
if(self.options.hideSpines===!1){var sPad=0;if(self.browser.msie8&&!self.browser.chromeFrame){sPad=Math.floor(($(self.spines[0]).outerWidth()-$($(self.spines[0]).find('cufon')[0]).height())/2)}
if(self.browser.safari||self.browser.chrome||self.browser.chromeFrame){if(document.doctype.publicId.toLowerCase().match(/transitional/)){sPad=Math.floor(($(self.spines[0]).outerHeight()-$($(self.spines[0]).find('cufon')[0]).height())/2)}}
self.spines.find('>cufon').css('margin-top',sPad)}})}};var bugSet=!1;var updateBug=function(){return!1};var updateControl=function(){if(self.options.controlProgress===!0){for(var i=0;i<self.spines.length;i++){if(i<self.controlTo){$(self.spines[i]).removeClass(self.classes.disabled)}else{$(self.spines[i]).addClass(self.classes.disabled)}}}};var hasVertical=function(event){var vertical=!1;if(typeof(self.verticalSlides)!=='undefined'){if(typeof(self.vertical().options)!=='undefined'){if(self.vertical().options.scroll===!0&&$(event.target).parents('.'+self.classes.vertical).length>0){vertical=!0}}}
return vertical};var autoPlay=function(){var vertical=!1,resetVertical=!1;var gotoNext=function(){if(self.options.device_width>700){var thisParent=$(self.spines).parent();if($(thisParent).parent().is('.lens-classic')){if($(thisParent).parent().is('.display-nav-always')){var spinesWidthNow=self.spines.height();var indexOfSpineNow=$('.lens-classic dt').index($('.active'));var lenSpine=$('.lens-classic dt').length;indexOfSpineNow=indexOfSpineNow+2;if(indexOfSpineNow===(lenSpine+1)&&!flagSpineShowAlways)
{indexOfSpineNow=1;if(jQuery(".slidedeck-frame.lens-classic > .slidedeck > dt").hasClass("sd2-spinePosition-horizontal")){$('.sd2-node-caption').css('left',indexOfSpineNow*spinesWidthNow+'px');$('.slide-content').css('left',indexOfSpineNow*spinesWidthNow+'px')}
else if(jQuery(".slidedeck-frame.lens-classic > .slidedeck > dt").hasClass("sd2-spinePosition-vertical")){$('.sd2-node-caption').css('top',indexOfSpineNow*spinesWidthNow+'px');$('.slide-content').css('top',indexOfSpineNow*spinesWidthNow+'px')}
indexOfSpineNow=lenSpine+1}else if(indexOfSpineNow<(lenSpine+1)&&!flagSpineShowAlways){}}}}
vertical=!1;if(self.pauseAutoPlay===!1&&self.options.autoPlay===!0){if(typeof(self.vertical())!=='undefined'){if(self.vertical().navChildren){if(self.vertical().current+1!==self.vertical().slides.length){vertical=!0}}}
var moveForward=!0;if(self.options.cycle===!1&&self.current===self.slides.length){if(vertical===!0){if(self.vertical().current+1===self.vertical().slides.length){moveForward=!1}}else{moveForward=!1}}
if(moveForward===!1){self.pauseAutoPlay=!0}else{if(vertical===!0){if(self.vertical().current+2===self.vertical().slides.length){vertical=!1;resetVertical=self.current}
self.vertical().next()}
else{if(self.slides.length===1&&self.current===self.slides.length){if(resetVertical!==!1){self.resetVertical(resetVertical,!1);resetVertical=!1}}
else{if(self.former!==-1){if(typeof(self.verticalSlides[self.former])!=='undefined'){if(typeof(self.verticalSlides[self.former].navChildren)!=='undefined'){self.resetVertical(self.former+1)}}}
self.next(function(deck){if(resetVertical!==!1){deck.resetVertical(resetVertical);resetVertical=!1}})}}}}
if(self.options.autoPlay==!0&&self.options.progressBar==!0&&self.pauseAutoPlay==!1){animateTimeline()}
setTimeout(gotoNext,self.options.autoPlayInterval)};if(self.options.progressBar==!0){animateTimeline()}
setTimeout(gotoNext,self.options.autoPlayInterval)};var resetTimeline=function(){var timeline=$("#sd2-progress-container");timeline.css({width:'0'},0);timeline.stop().css({width:'0',opacity:1,height:'3px'},0)};var animateTimeline=function(){var barColor=self.options.progressBarColor;time=self.options.autoPlayInterval;var timeline=$("#sd2-progress-container");timeline.stop().css({width:'0',opacity:1,height:'3px',background:barColor},0);timeline.stop().animate({width:'100%',height:'3px',background:barColor},time,'easeInOutQuint',function(){$(this).animate({opacity:0,width:0,height:'3px',background:barColor})})};var buildSlideTransition=function(transition,i){if(self.options.hideSpines===!0){var slideCSS={display:'block'}}else{var slideCSS={}}
slideCSS[prefix+'transform-origin']="50% 50%";slideCSS[prefix+'transform']="";if(i<self.current){var offset=i*spine_outer_width;if(self.options.hideSpines===!0){if(i===self.current-1){offset=0}else{offset=0-(self.options.start-i-1)*el.width()}}}else{slide_width=width-spine_outer_width*self.spines.length;if(self.options.hideSpines===!0){slide_width=width}
if(jQuery(".slidedeck-frame.lens-classic > .slidedeck > dt").hasClass("sd2-spinePosition-horizontal")){var offset=i*spine_outer_width+slide_width}
else if(jQuery(".slidedeck-frame.lens-classic > .slidedeck > dt").hasClass("sd2-spinePosition-vertical")){var offset=height-((self.slides.length-i)*spine_outer_width)}
if(self.options.hideSpines===!0){offset=(i+1-self.options.start)*el.width()}
if(jQuery(".slidedeck-frame.lens-tool-kit.sd2-fullwidth").find("dd")&&!jQuery(".slidedeck-frame").hasClass("lens-classic"))
{offset=(i+1-self.options.start)*jQuery(window).width()}
else if(jQuery(".slidedeck-frame.lens-vanilla.sd2-fullwidth").find("dd")&&!jQuery(".slidedeck-frame").hasClass("lens-classic"))
{offset=(i+1-self.options.start)*jQuery(window).width()}
else if(jQuery(".slidedeck-frame.lens-infinity.sd2-fullwidth").find("dd")&&!jQuery(".slidedeck-frame").hasClass("lens-classic"))
{offset=(i+1-self.options.start)*jQuery(window).width()}
else if(jQuery(".slidedeck-frame.lens-testimonial.sd2-fullwidth").find("dd")&&!jQuery(".slidedeck-frame").hasClass("lens-classic"))
{offset=(i+1-self.options.start)*jQuery(window).width()}}
switch(transition){case "stack":slideCSS.zIndex=self.slides.length-i;slideCSS.left=0;break;case "fade":var $currentSlide=self.slides.eq(self.current-1);slideCSS.zIndex=self.slides.length-i;slideCSS.left=0;self.slides.not($currentSlide).css({opacity:0});break;case "flip":slideCSS.zIndex=self.slides.length-i;slideCSS.left=0;if(i!==(self.current-1)){slideCSS[prefix+'transform']="scaleY(0)"}
break;case "flipHorizontal":slideCSS.zIndex=self.slides.length-i;slideCSS.left=0;if(i!==(self.current-1)){slideCSS[prefix+'transform']="scaleX(0)"}
break;case "slide":default:slideCSS.left=offset;slideCSS.zIndex=1;break}
self.slides.eq(i).css(prefix+'transition',"").css(slideCSS);return offset};var autoAdjustHeight=function(){var slide=$(self.slides[self.current-1]);var vertical=!1;if(typeof(self.vertical())!=='undefined'){if(self.vertical().navChildren){if(self.vertical().current+1!==self.vertical().slides.length){vertical=!0}}}
if((self.options.auto_height||screen.width<700)&&self.options.hideSpines===!0&&vertical===!1){var image=slide.find('img.sd2-slide-background');if(image.length!==0){image.on('load',function(){adjustSlideHeight(slide)}).each(function(){if(this.complete)$(this).load()})}else{adjustSlideHeight(slide)}}else{if(vertical){slide=self.vertical().slides[self.current-1]}
slidedeckAdjustImage(slide)}}
var adjustSlideHeight=function(slide){var slide_actual_height=0;$(slide).children('img, div').each(function(){var pad_top=0;var bottom=0;if($(this).hasClass('slide-content')){pad_top=jQuery(this).css('padding-top');bottom=jQuery(this).css('bottom')}
var div_height=this.clientHeight;if($(this).find('.slide-content').length){div_height=$(this).find('.slide-content').height();pad_top=$(this).find('.slide-content').css('padding-top');bottom=$(this).find('.slide-content').css('bottom')}
if(div_height>slide_actual_height){slide_actual_height=div_height+parseInt(pad_top)+parseInt(bottom)}});if(parseInt(slide_actual_height)<20&&self.options.device_width>700){slide_actual_height=height}else if(parseInt(slide_actual_height)<20&&self.options.device_width<700){slide_actual_height=200}
self.slides.context.style.height=slide_actual_height+"px";slide.css('height',slide_actual_height+"px");var preview_iframe=parent.document.getElementById('slidedeck-preview');if(preview_iframe!==null){var nav_height=jQuery('.slidedeck-frame .sd-nav-wrapper').height();preview_iframe.style.height=slide_actual_height+nav_height+100+"px"}}
var buildDeck=function(){if($.inArray(el.css('position'),['position','absolute','fixed'])){el.css('position','relative')}
el.css('overflow','hidden');for(var i=0;i<self.slides.length;i++){var slide=$(self.slides[i]);if(self.spines.length>i){var spine=$(self.spines[i])}
var sPad={top:parseInt(slide.css('padding-top'),10),right:parseInt(slide.css('padding-right'),10),bottom:parseInt(slide.css('padding-bottom'),10),left:parseInt(slide.css('padding-left'),10)};var sBorder={top:parseInt(slide.css('border-top-width'),10),right:parseInt(slide.css('border-right-width'),10),bottom:parseInt(slide.css('border-bottom-width'),10),left:parseInt(slide.css('border-left-width'),10)};for(var k in sBorder){sBorder[k]=isNaN(sBorder[k])?0:sBorder[k]}
if(i<self.current){if(i===self.current-1){if(self.options.hideSpines!==!0){spine.addClass(self.classes.active)}
slide.addClass(self.classes.active)}}
if(self.options.hideSpines===!1){slide_width=width}
self.slide_width=(slide_width-sPad.left-sPad.right-sBorder.left-sBorder.right);if(jQuery(".lens-tool-kit").hasClass("sd2-fullwidth")){self.slide_width=(jQuery(window).width()-sPad.left-sPad.right-sBorder.left-sBorder.right)}
if(jQuery(".lens-vanilla").hasClass("sd2-fullwidth")){self.slide_width=(jQuery(window).width()-sPad.left-sPad.right-sBorder.left-sBorder.right)}
if(jQuery(".lens-infinity").hasClass("sd2-fullwidth")){self.slide_width=(jQuery(window).width()-sPad.left-sPad.right-sBorder.left-sBorder.right)}
var slide_height=(height-sPad.top-sPad.bottom-sBorder.top-sBorder.bottom)+"px"
if(jQuery(".lens-testimonial").hasClass("sd2-fullwidth")){self.slide_width=(jQuery(window).width()-sPad.left-sPad.right-sBorder.left-sBorder.right),slide_height=height+"px"}
var slideCSS={position:'absolute',height:slide_height,width:self.slide_width+"px",margin:0,paddingLeft:sPad.left+"px",};var offset=buildSlideTransition(self.options.slideTransition,i);slide.css(slideCSS).addClass(self.classes.slide).addClass(self.classes.slide+"_"+(i+1));if(self.options.hideSpines!==!0){var spinePad={top:parseInt(spine.css('padding-top'),10),right:parseInt(spine.css('padding-right'),10),bottom:parseInt(spine.css('padding-bottom'),10),left:parseInt(spine.css('padding-left'),10)};for(var l in spinePad){if(spinePad[l]<10&&(l==="left"||l==="right")){spinePad[l]=10}}
var spinePadString=spinePad.top+"px "+spinePad.right+"px "+spinePad.bottom+"px "+spinePad.left+"px";if(jQuery(".slidedeck-frame.lens-classic > .slidedeck > dt").hasClass("sd2-spinePosition-horizontal")){var spineStyles={position:'absolute',zIndex:3,left:offset,width:(height)+"px",height:spine_inner_width+"px",padding:spinePadString,rotation:'270deg','-webkit-transform':'rotate(270deg)','-webkit-transform-origin':spine_half_width+'px 0px','-moz-transform':'rotate(270deg)','-moz-transform-origin':spine_half_width+'px 0px','-ms-transform':'rotate(270deg)','-ms-transform-origin':spine_half_width+'px 0px','-o-transform':'rotate(270deg)','-o-transform-origin':spine_half_width+'px 0px',textAlign:'right'}}
else if(jQuery(".slidedeck-frame.lens-classic > .slidedeck > dt").hasClass("sd2-spinePosition-vertical")){var spineStyles={position:'absolute',zIndex:3,left:0+"px",top:offset,width:(self.slide_width)+"px",height:spine_inner_width+"px",padding:spinePadString,rotation:'0deg','-webkit-transform':'rotate(0deg)','-webkit-transform-origin':spine_half_width+'px 0px','-moz-transform':'rotate(0deg)','-moz-transform-origin':spine_half_width+'px 0px','-ms-transform':'rotate(0deg)','-ms-transform-origin':spine_half_width+'px 0px','-o-transform':'rotate(0deg)','-o-transform-origin':spine_half_width+'px 0px',textAlign:'right'};jQuery(".slidedeck-frame.lens-classic > .slidedeck > dd").css("left",0+"px")}
if(!self.browser.msie9&&!self.browser.msie10){if(jQuery(".slidedeck-frame.lens-classic > .slidedeck > dt").hasClass("sd2-spinePosition-horizontal")){spineStyles.top=(self.browser.msie)?0:(height-spine_half_width)+"px"}
spineStyles.marginLeft=((self.browser.msie)?0:(0-spine_half_width))+"px";var dir=document.getElementsByTagName('html')[0].dir;if(dir.toLowerCase()==="rtl"&&self.browser.msie8===!0){spineStyles.marginLeft=(0-height+spine_half_width*2)+"px"}
spineStyles.filter='progid:DXImageTransform.Microsoft.BasicImage(rotation=3)'}
spine.css(spineStyles).addClass(self.classes.spine).addClass(self.classes.spine+"_"+(i+1));if(self.browser.msie9||self.browser.msie10){spine[0].style.msTransform='rotate(270deg)';spine[0].style.msTransformOrigin=Math.round(parseInt(el[0].style.height,10)/2)+'px '+Math.round(parseInt(el[0].style.height,10)/2)+'px'}}else{if(typeof(spine)!=="undefined"){spine.hide()}}
if(i===self.slides.length-1){slide.addClass('last');if(self.options.hideSpines!==!0){spine.addClass('last')}}
if(self.options.activeCorner===!0&&self.options.hideSpines===!1){var corner=document.createElement('DIV');corner.className=self.classes.activeCorner+' '+(self.classes.spine+'_'+(i+1));spine.after(corner);spine.next('.'+self.classes.activeCorner).css({position:'absolute',top:'25px',left:offset+spine_outer_width+"px",overflow:"hidden",zIndex:"20000"}).hide();if(spine.hasClass(self.classes.active)){spine.next('.'+self.classes.activeCorner).show()}}
if(self.options.hideSpines!==!0){var index=document.createElement('DIV');index.className=self.classes.index;if(self.options.index!==!1){var textNode;if(typeof(self.options.index)!=='boolean'){textNode=self.options.index[i%self.options.index.length]}else{textNode=""+(i+1)}
index.appendChild(document.createTextNode(textNode))}
spine.append(index);if(jQuery(".slidedeck-frame.lens-classic > .slidedeck > dt").hasClass("sd2-spinePosition-horizontal")){spine.find('.'+self.classes.index).css({position:'absolute',zIndex:2,display:'block',width:spine_inner_width+"px",height:spine_inner_width+"px",textAlign:'center',bottom:((self.browser.msie)?0:(0-spine_half_width))+"px",left:((self.browser.msie)?5:20)+"px",rotation:"90deg",'-webkit-transform':'rotate(90deg)','-webkit-transform-origin':spine_half_width+'px 0px','-moz-transform':'rotate(90deg)','-moz-transform-origin':spine_half_width+'px 0px','-o-transform':'rotate(90deg)','-o-transform-origin':spine_half_width+'px 0px'});if(self.browser.msie9||self.browser.msie10){spine.find('.'+self.classes.index)[0].style.msTransform='rotate(90deg)'}
if(!self.browser.msie){spine.find('.'+self.classes.index).css({'-ms-transform':'rotate(90deg)','-ms-transform-origin':spine_half_width+'px 0px'})}}
else if(jQuery(".slidedeck-frame.lens-classic > .slidedeck > dt").hasClass("sd2-spinePosition-vertical")){spine.find('.'+self.classes.index).css({position:'absolute',zIndex:2,display:'block',width:spine_inner_width+"px",height:spine_inner_width+"px",textAlign:'center',bottom:((self.browser.msie)?0:(0-parseInt(spine_outer_width/3)))+"px",left:((self.browser.msie)?5:20)+"px",rotation:"0deg",'-webkit-transform':'rotate(0deg)','-webkit-transform-origin':spine_half_width+'px 0px','-moz-transform':'rotate(0deg)','-moz-transform-origin':spine_half_width+'px 0px','-o-transform':'rotate(0deg)','-o-transform-origin':spine_half_width+'px 0px'});if(self.browser.msie9||self.browser.msie10){spine.find('.'+self.classes.index)[0].style.msTransform='rotate(0deg)'}
if(!self.browser.msie){spine.find('.'+self.classes.index).css({'-ms-transform':'rotate(0deg)','-ms-transform-origin':spine_half_width+'px 0px'})}}
FixIEAA(spine)}}
updateBug();if(self.options.hideSpines!==!0){self.spines.bind('click',function(event){event.preventDefault();if(self.options.device_width>700){var thisParent=$(this).parent();if($(thisParent).parent().is('.lens-classic')){if($(thisParent).parent().is('.display-nav-always')){var spinesWidthsNow=self.spines.height();if(jQuery(".slidedeck-frame.lens-classic > .slidedeck > dt").hasClass("sd2-spinePosition-horizontal")){$('.sd2-node-caption').css('left',(self.spines.index(this)+1)*spinesWidthsNow+'px');$('.slide-content').css('left',(self.spines.index(this)+1)*spinesWidthsNow+'px')}
else if(jQuery(".slidedeck-frame.lens-classic > .slidedeck > dt").hasClass("sd2-spinePosition-vertical")){$('.sd2-node-caption').css('top',(self.spines.index(this)+1)*spinesWidthsNow+'px');$('.slide-content').css('top',(self.spines.index(this)+1)*spinesWidthsNow+'px')}
flagSpineShowAlways=!0}}}
self.goTo(self.spines.index(this)+1)})}
$(document).bind('keydown',function(event){if(!$(self.deck).closest(".lens-prime").length&&!$(self.deck).closest(".lens-parfocal").length&&!$(self.deck).closest(".lens-parallax").length&&!$(self.deck).closest(".lens-layerpro").length){if(self.options.keys!==!1){if($(event.target).parents().index(self.deck)===-1){if(event.keyCode===39){self.pauseAutoPlay=!0;self.next()}else if(event.keyCode===37){self.pauseAutoPlay=!0;self.prev()}}}}});if(typeof($.event.special.mousewheel)!=="undefined"){el.bind("mousewheel",function(event,mousewheeldelta){if(!$(self.deck).closest(".lens-prime").length&&!$(self.deck).closest(".lens-parfocal").length&&!$(self.deck).closest(".lens-parallax").length&&!$(self.deck).closest(".lens-layerpro").length){if(self.options.scroll!==!1){if(!hasVertical(event)){var delta=event.detail?event.detail:event.wheelDelta;if(typeof(delta)==='undefined'){delta=0-mousewheeldelta}
var internal=!1;if($(event.originalTarget).parents(self.deck).length){if($.inArray(event.originalTarget.nodeName.toLowerCase(),['input','select','option','textarea'])!==-1){internal=!0}}
if(internal!==!0){if(delta>0){switch(self.options.scroll){case "stop":event.preventDefault();break;case true:default:if(self.current<self.slides.length||self.options.cycle===!0){event.preventDefault()}
break}
self.pauseAutoPlay=!0;self.next()}
else{switch(self.options.scroll){case "stop":event.preventDefault();break;case true:default:if(self.current!==1||self.options.cycle===!0){event.preventDefault()}
break}
self.pauseAutoPlay=!0;self.prev()}}}}}})}
if((self.browser.msie!==!0)&&(self.options.touch!==!1)){var originalCoords={x:0,y:0};var finalCoords={x:0,y:0};var threshold=self.options.touchThreshold;el[0].addEventListener('touchstart',function(event){originalCoords.x=event.targetTouches[0].pageX;originalCoords.y=event.targetTouches[0].pageY},!1);el[0].addEventListener('touchmove',function(event){event.preventDefault();finalCoords.x=event.targetTouches[0].pageX;finalCoords.y=event.targetTouches[0].pageY},!1);el[0].addEventListener('touchend',function(event){var limitLeft=originalCoords.x-threshold.x;var limitRight=originalCoords.x+threshold.x;var limitUp=originalCoords.y-threshold.y;var limitDown=originalCoords.y+threshold.y;if(finalCoords.x!==0){if(finalCoords.x<=limitLeft){self.pauseAutoPlay=!0;self.next()}else if(finalCoords.x>=limitRight){self.pauseAutoPlay=!0;self.prev()}}
if(finalCoords.y!==0){if(finalCoords.y<=limitUp){self.pauseAutoPlay=!0;self.vertical().next()}else if(finalCoords.y>=limitDown){self.pauseAutoPlay=!0;self.vertical().prev()}}
originalCoords={x:0,y:0};finalCoords={x:0,y:0}},!1)}
$(self.spines[self.current-2]).addClass(self.classes.previous);$(self.spines[self.current]).addClass(self.classes.next);updateAddons();updateControl();if(self.isLoaded===!1){autoPlay()}
self.isLoaded=!0};var getPrevValidSlide=function(ind){ind=Math.max(1,ind-1);if($.inArray(ind,self.disabledSlides)!==-1){if(ind===1){ind=1}else{ind=getPrevValidSlide(ind)}}
return ind};var getNextValidSlide=function(ind){ind=Math.min(self.slides.length,ind+1);if($.inArray(ind,self.disabledSlides)!==-1){if(ind===self.slides.length){ind=self.current}
else{ind=getNextValidSlide(ind)}}
return ind};var getValidSlide=function(ind){ind=Math.min(self.slides.length,Math.max(1,ind));if($.inArray(ind,self.disabledSlides)!==-1){if(ind<self.current){ind=getPrevValidSlide(ind)}
else{ind=getNextValidSlide(ind)}}
return ind};var completeCallback=function(params){var afterFunctions=[];if(typeof(self.options.complete)==="function"){afterFunctions.push(function(){self.options.complete(self)})}
switch(typeof(params)){case "function":afterFunctions.push(function(){params(self)});break;case "object":afterFunctions.push(function(){params.complete(self)});break}
var callbackFunction=function(){self.looping=!1;for(var z=0;z<afterFunctions.length;z++){afterFunctions[z](self)}};return callbackFunction};var transitions={fade:function(ind,params,forward){var $currentSlide=self.slides.eq(self.current-1);self.slides.not($currentSlide).stop().animate({opacity:0},self.options.speed,function(){this.style.display="none"});$currentSlide.css({display:'block',opacity:0}).addClass(self.classes.active).stop().animate({opacity:1},self.options.speed,function(){this.style.display="block";completeCallback(params)()});if(self.options.auto_height||self.options.device_width<700){var slide_actual_height=0;$($currentSlide).children('img, div').each(function(){var pad_top=0;var bottom=0;if($(this).hasClass('slide-content')){pad_top=jQuery(this).css('padding-top');bottom=jQuery(this).css('bottom')}
var div_height=this.clientHeight;if($(this).find('.slide-content').length){div_height=$(this).find('.slide-content').height();pad_top=$(this).find('.slide-content').css('padding-top');bottom=$(this).find('.slide-content').css('bottom')}
if(div_height>slide_actual_height){slide_actual_height=div_height+parseInt(pad_top)+parseInt(bottom)}});if(parseInt(slide_actual_height)<20&&self.options.device_width>700){slide_actual_height=height}else if(parseInt(slide_actual_height)<20&&self.options.device_width<700){slide_actual_height=200}
slide_height=slide_actual_height;$currentSlide.css('height',slide_height);$currentSlide.context.style.transition="all 1s";$currentSlide.context.style.height=slide_height+"px";var preview_iframe=parent.document.getElementById('slidedeck-preview');if(preview_iframe!==null){var nav_height=jQuery('.slidedeck-frame .sd-nav-wrapper').height();preview_iframe.style.height=slide_height+nav_height+100+"px"}}else{slidedeckAdjustImage($currentSlide)}},flip:function(ind,params,forward,horizontal){var secondsSpeed=(self.options.speed/1000)/2;var $formerSlide=self.slides.eq(self.former-1);var $currentSlide=self.slides.eq(self.current-1);if(typeof(horizontal)==='undefined'){horizontal=!1}
var direction=horizontal===!0?"X":"Y";if(self.options.auto_height||self.options.device_width<700){var slide_actual_height=0;$($currentSlide).children('img, div').each(function(){var pad_top=0;var bottom=0;if($(this).hasClass('slide-content')){pad_top=jQuery(this).css('padding-top');bottom=jQuery(this).css('bottom')}
var div_height=this.clientHeight;if($(this).find('.slide-content').length){div_height=$(this).find('.slide-content').height();pad_top=$(this).find('.slide-content').css('padding-top');bottom=$(this).find('.slide-content').css('bottom')}
if(div_height>slide_actual_height){slide_actual_height=div_height+parseInt(pad_top)+parseInt(bottom)}});if(parseInt(slide_actual_height)<20&&self.options.device_width>700){slide_actual_height=height}else if(parseInt(slide_actual_height)<20&&self.options.device_width<700){slide_actual_height=200}
slide_height=slide_actual_height;$currentSlide.css('height',slide_height);$currentSlide.context.style.transition="all 1s";$currentSlide.context.style.height=slide_height+"px";var preview_iframe=parent.document.getElementById('slidedeck-preview');if(preview_iframe!==null){var nav_height=jQuery('.slidedeck-frame .sd-nav-wrapper').height();preview_iframe.style.height=slide_height+nav_height+100+"px"}}else{slidedeckAdjustImage($currentSlide)}
var maskCSS={position:'absolute',zIndex:999,top:0,right:0,bottom:0,left:0,width:'100%',height:'100%',opacity:0};var $formerMask=$formerSlide.find('.slidedeck-slide-mask');if($formerMask.length){$formerMask.remove()}
$formerSlide.append('<div class="slidedeck-slide-mask mask-out"></div>');$formerMask=$formerSlide.find('.slidedeck-slide-mask').css(maskCSS);var $currentMask=$currentSlide.find('.slidedeck-slide-mask');if($currentMask.length){$formerMask.remove()}
$currentSlide.addClass(self.classes.active).append('<div class="slidedeck-slide-mask mask-in"></div>');maskCSS.opacity=1;$currentMask=$currentSlide.find('.slidedeck-slide-mask').css(maskCSS);var resetCSS={};resetCSS[prefix+'transition']="";resetCSS[prefix+'transform-origin']="50% 50%";resetCSS[prefix+'transform']="scale"+direction+"(0)";self.slides.not($formerSlide).css(resetCSS);var animateCSS={};animateCSS[prefix+'transform-origin']="50% 50%";animateCSS[prefix+'transform']="scale"+direction+"(0)";$formerSlide.css(prefix+'transition',prefix+'transform '+secondsSpeed+'s ease-out').css(animateCSS);$formerMask.animate({opacity:1},{duration:self.options.speed/2,complete:function(){$formerMask.remove()}});$currentMask.animate({opacity:1},{duration:self.options.speed/2,complete:function(){animateCSS[prefix+'transform']="scale"+direction+"(1)";$currentSlide.addClass(self.classes.active).css(prefix+'transition',prefix+'transform '+secondsSpeed+'s ease-out').css(animateCSS);$currentMask.animate({opacity:0},{dureation:self.options.speed/2,complete:function(){self.slides.css(prefix+'transition',"");var finishCSS={};finishCSS[prefix+'transform-origin']="50% 50%";finishCSS[prefix+'transform']="scale"+direction+"(1)";self.slides.eq(self.current-1).css(finishCSS);completeCallback(params)();$formerMask.remove();$currentMask.remove()}})}})},flipHorizontal:function(ind,params,forward){this.flip(ind,params,forward,!0)},stack:function(ind,params,forward){if((self.current===self.slides.length&&self.former===1)||(self.former===self.slides.length&&self.current===1)){self.looping=!0}
for(var i=0;i<self.slides.length;i++){var pos=0;var slide=self.slides.eq(i);if(self.looping===!1){if(i<self.current-1){if(i===(self.current-1)){slide.addClass(self.classes.active);updateAddons()}
pos=(0-width)}
else{pos=0}}else{if(self.former===self.slides.length&&self.current===1){if(i===(self.current)-1){slide.css({left:0,zIndex:5}).addClass(self.classes.active);updateAddons();pos=0}else{if(i===(self.former-1)){slide.css('z-index',10);pos=0-width}else{slide.css('z-index',1);pos=0}}}else if(self.former===1&&self.current===self.slides.length){if(i!==self.former-1){if(i===(self.current-1)){slide.css({left:(0-width),zIndex:100});slide.addClass(self.classes.active);updateAddons();pos=0}}}}
var animOpts={duration:self.options.speed,easing:self.options.transition};if(i===(forward===!0&&self.current-1)||i===(forward===!1&&self.current)){animOpts.complete=function(){if(self.looping===!0){self.slides.each(function(ind){if(ind!==(self.current-1)){this.style.left=(self.current===1?0:(0-width))+"px"}
this.style.zIndex=self.slides.length-ind})}
completeCallback(params)()}}
var slide_height=height;if(self.options.auto_height||self.options.device_width<700){if(i===(self.current-1)){var slide_actual_height=0;$(slide).children('img, div').each(function(){var pad_top=0;var bottom=0;if($(this).hasClass('slide-content')){pad_top=jQuery(this).css('padding-top');bottom=jQuery(this).css('bottom')}
var div_height=this.clientHeight;if($(this).find('.slide-content').length){div_height=$(this).find('.slide-content').height();pad_top=$(this).find('.slide-content').css('padding-top');bottom=$(this).find('.slide-content').css('bottom')}
if(div_height>slide_actual_height){slide_actual_height=div_height+parseInt(pad_top)+parseInt(bottom)}});if(parseInt(slide_actual_height)<20&&self.options.device_width>700){slide_actual_height=height}else if(parseInt(slide_actual_height)<20&&self.options.device_width<700){slide_actual_height=200}
slide_height=slide_actual_height;self.slides.context.style.height=slide_height+"px";var preview_iframe=parent.document.getElementById('slidedeck-preview');if(preview_iframe!==null){var nav_height=jQuery('.slidedeck-frame .sd-nav-wrapper').height();preview_iframe.style.height=slide_height+nav_height+100+"px"}}
slide.stop().animate({left:pos,width:self.slide_width,height:slide_height},animOpts)}else{slide.stop().animate({left:pos,width:self.slide_width,height:height},animOpts);if(i===(self.current-1)){slidedeckAdjustImage(slide)}}}},slide:function(ind,params,forward){for(var i=0;i<self.slides.length;i++){var pos=spine_pos=0;if(self.options.hideSpines!==!0){var spine=$(self.spines[i])}
var slide=$(self.slides[i]);if(i<self.current){if(i===(self.current-1)){slide.addClass(self.classes.active);if(self.options.hideSpines!==!0){spine.addClass(self.classes.active);spine.next('.'+self.classes.activeCorner).show()}
updateAddons()}
pos=i*spine_outer_width}
else if(self.options.start==self.slides.length){if(jQuery(".slidedeck-frame.lens-classic > .slidedeck > dt").hasClass("sd2-spinePosition-horizontal")){pos=(slide_width-(i*spine_outer_width))}
else if(jQuery(".slidedeck-frame.lens-classic > .slidedeck > dt").hasClass("sd2-spinePosition-vertical")){pos=(slide_height-((self.slides.length-i)*spine_outer_width))}}
else if(self.options.start!=self.slides.length){if(jQuery(".slidedeck-frame.lens-classic > .slidedeck > dt").hasClass("sd2-spinePosition-horizontal")){spine_pos=i*spine_outer_width
pos=spine_pos+slide_width}
else if(jQuery(".slidedeck-frame.lens-classic > .slidedeck > dt").hasClass("sd2-spinePosition-vertical")){spine_pos=(self.slides.length-i)*spine_outer_width;pos=slide_height-spine_pos}}
if(jQuery(self.deck.parent()).is('.display-nav-always')){if(jQuery(".slidedeck-frame.lens-classic > .slidedeck > dt").hasClass("sd2-spinePosition-horizontal")){jQuery('.lens-classic .slide img').css('left',(self.current*spine_outer_width))}
else if(jQuery(".slidedeck-frame.lens-classic > .slidedeck > dt").hasClass("sd2-spinePosition-vertical")){jQuery('.lens-classic .slide img').css('top',(self.current*spine_outer_width))}}
if(self.options.hideSpines===!0){pos=(i-self.current+1)*el.width();if(jQuery(".slidedeck-frame.lens-classic > .slidedeck > dt").hasClass("sd2-spinePosition-horizontal")){pos=(i-self.current+1)*el.width()}
else if(jQuery(".slidedeck-frame.lens-classic > .slidedeck > dt").hasClass("sd2-spinePosition-vertical")){pos=((self.slides.length-i)-self.current+1)*el.height()}}
var animOpts={duration:self.options.speed,easing:self.options.transition};if(i===0){animOpts.complete=completeCallback(params)}
var slide_height=height;if(jQuery(slide).closest('.lens-titles').length>0){var nav_height=jQuery('.slidedeck-frame .button-nav').height();var padd=Math.round(parseInt(jQuery('.slidedeck-frame .button-nav').css('padding-top')));slide_height=slide_height-parseInt(nav_height)-parseInt(padd)-15}
$(slide).children('img').each(function(){$(this).css('margin-left','0px')});if(i===(self.current-1)&&(self.options.auto_height||self.options.device_width<700)){var slide_actual_height=0;$(slide).children('img, div').each(function(){var pad_top=0;var bottom=0;if($(this).hasClass('slide-content')){pad_top=jQuery(this).css('padding-top');bottom=jQuery(this).css('bottom')}
var div_height=this.clientHeight;if($(this).find('.slide-content').length){div_height=$(this).find('.slide-content').height();pad_top=$(this).find('.slide-content').css('padding-top');bottom=$(this).find('.slide-content').css('bottom')}
if(div_height>slide_actual_height){slide_actual_height=div_height+parseInt(pad_top)+parseInt(bottom)}});if(parseInt(slide_actual_height)<20&&self.options.device_width>700){slide_actual_height=height}else if(parseInt(slide_actual_height)<20&&self.options.device_width<700){slide_actual_height=200}
slide_height=slide_actual_height;var preview_iframe=parent.document.getElementById('slidedeck-preview');if(preview_iframe!==null){var nav_height=jQuery('.slidedeck-frame .sd-nav-wrapper').height();preview_iframe.style.height=slide_actual_height+nav_height+100+"px"}
self.slides.context.style.height=slide_height+"px"}
if(self.options.hideSpines===!0){if(self.options.auto_height||self.options.device_width<700){slide.stop().animate({left:pos+"px",width:self.slide_width+"px",height:slide_height},animOpts)}else{var sPad={top:parseInt(slide.css('padding-top'),10),right:parseInt(slide.css('padding-right'),10),bottom:parseInt(slide.css('padding-bottom'),10),left:parseInt(slide.css('padding-left'),10)};var dd_height=height;if(slide.closest('.layout-three-wide').length>0||slide.closest('.layout-peek').length>0){height=(height-sPad.top-sPad.bottom)+"px"}
if(jQuery(slide).closest('.lens-titles').length>0){var nav_height=jQuery('.slidedeck-frame .button-nav').height();var padd=Math.round(parseInt(jQuery('.slidedeck-frame .button-nav').css('padding-top')));dd_height=height-parseInt(nav_height)-parseInt(padd)-15}
if(slide.find('.slidedeck-vertical-center-inner').length>0){var nav_height=jQuery('.nav-slidedeck').height();var new_height=(parseInt(height)-nav_height)+"px";slide.stop().animate({left:pos+"px",width:self.slide_width+"px",height:new_height},animOpts)}else{slide.stop().animate({left:pos+"px",width:self.slide_width+"px",height:dd_height},animOpts)}
if(i===(self.current-1)){slidedeckAdjustImage(slide)}}}else{if(jQuery(".slidedeck-frame.lens-classic > .slidedeck > dt").hasClass("sd2-spinePosition-horizontal")){var left_offset=0;if(i===(self.current-1)){left_offset=0}else{left_offset=pos}
slide.stop().animate({left:left_offset+"px",width:width+"px"},animOpts)}
else if(jQuery(".slidedeck-frame.lens-classic > .slidedeck > dt").hasClass("sd2-spinePosition-vertical")){var top_offset=0;if(i===(self.current-1)){top_offset=0}else{top_offset=pos}
slide.stop().animate({top:top_offset+"px",left:0+"px",width:width+"px"},animOpts)}}
if(self.options.hideSpines!==!0){if(i===(self.current-1)){slidedeckAdjustImage(slide)}
FixIEAA(spine);if(spine.css('left')!==pos+"px"){if(jQuery(".slidedeck-frame.lens-classic > .slidedeck > dt").hasClass("sd2-spinePosition-horizontal")){spine.stop().animate({left:pos+"px"},{duration:self.options.speed,easing:self.options.transition});spine.next('.'+self.classes.activeCorner).stop().animate({left:pos+spine_outer_width+"px"},{duration:self.options.speed,easing:self.options.transition})}
else if(jQuery(".slidedeck-frame.lens-classic > .slidedeck > dt").hasClass("sd2-spinePosition-vertical")){spine.stop().animate({top:pos+"px",left:0+"px"},{duration:self.options.speed,easing:self.options.transition});spine.next('.'+self.classes.activeCorner).stop().animate({top:slide_height-spine_pos+"px",left:0+"px"},{duration:self.options.speed,easing:self.options.transition})}}}}}};var slide=function(ind,params){ind=getValidSlide(ind);if((ind<=self.controlTo||self.options.controlProgress!==!0)&&self.looping===!1){var forward=!0;if(ind<self.current){forward=!1}
var classReset=[self.classes.active,self.classes.next,self.classes.previous].join(' ');self.former=self.current;self.current=ind;if(typeof(self.options.before)==="function"){self.options.before(self)}
if(typeof(params)!=="undefined"){if(typeof(params.before)==="function"){params.before(self)}}
if(self.current!==self.former){self.spines.removeClass(classReset);self.slides.removeClass(classReset);el.find('.'+self.classes.activeCorner).hide();self.spines.eq(self.current-2).addClass(self.classes.previous);self.spines.eq(self.current).addClass(self.classes.next);var slideTransition='slide';if(typeof(transitions[self.options.slideTransition])!=='undefined'){slideTransition=self.options.slideTransition}
transitions[slideTransition](ind,params,forward)}
$(window).trigger('slidedeckChange',[self.slides,ind]);updateBug()}};var setOption=function(opts,val){var newOpts=opts;if(typeof(opts)==="string"){newOpts={};newOpts[opts]=val}
for(var key in newOpts){val=newOpts[key];switch(key){case "speed":case "start":val=parseFloat(val);if(isNaN(val)){val=self.options[key]}
break;case "autoPlay":if(typeof(val)!=="boolean"){val=self.options[key]}
self.pauseAutoPlay=!1;break;case "scroll":case "keys":case "activeCorner":case "controlProgress":case "hideSpines":case "cycle":if(typeof(val)!=="boolean"){val=self.options[key]}
break;case "cufonRefresh":case "transition":if(typeof(val)!=="string"){val=self.options[key]}
break;case "complete":case "before":if(typeof(val)!=="function"){val=self.options[key]}
break;case "index":if(typeof(val)!=="boolean"){if(!$.isArray(val)){val=self.options[key]}}
break;case "slideTransition":for(var k in transitions){if(val===k){switch(self.browser._this){case "msie":case "msie7":case "msie8":case "msie9":case "msie10":switch(val){case "flip":case "flipHorizontal":val="fade";break}
break}
self.options.slideTransition=val;for(var i=0;i<self.slides.length;i++){buildSlideTransition(self.options.slideTransition,i)}}}
break}
self.options[key]=val}};var disableSlide=function(ind){if($.inArray(ind,self.disabledSlides)===-1&&ind!==1&&ind!==0){self.disabledSlides.push(ind)}};var enableSlide=function(ind){var indIndex=$.inArray(ind,self.disabledSlides);if(indIndex!==-1){self.disabledSlides.splice(indIndex,1)}};var VerticalSlide=function(el,deck,opts){var self=this;var el=$(el);var elChildren=el.children();if(el[0].nodeName==="DL"){elChildren=el.children('dd');var elNavTitles=el.children('dt').hide()}
var total=elChildren.length;var parentSlide=el.parents('dd.slide');var elParent=el.parent();var height=parentSlide.innerHeight();var zIndex=100;if(deck.deck.find('.'+deck.classes.activeCorner).length){zIndex=deck.deck.find('.'+deck.classes.activeCorner).css('z-index')-1}
this.navParent=null;this.navChildren=null;this.current=0;this.slides=elChildren;this.options={speed:500,scroll:!0,continueScrolling:deck.options.continueScrolling};if(typeof(opts)==='object'){for(var k in opts){this.options[k]=opts[k]}}
this.classes={navContainer:'verticalSlideNav',arrow:'arrow',prefix:'verticalSlide'};var slide=function(index,snap,callback){self.current=index;if(typeof(self.options.before)==='function'){self.options.before(self)}
if(typeof(callback)==='object'){if(typeof(callback.before)==='function'){callback.before(self)}}
var speed=self.options.speed;if(typeof(snap)!=='undefined'){speed=0}
speed=parseInt(speed,10);parentSlide.find('ul.'+self.classes.navContainer+' li.'+self.classes.arrow).stop().animate({top:$(self.navChildren[self.current]).position().top+'px'},speed);self.navChildren.removeClass(deck.classes.active);$(self.navChildren[self.current]).addClass(deck.classes.active);self.slides.removeClass(deck.classes.active);$(self.slides[index]).addClass(deck.classes.active);slidedeckAdjustImage(self.slides[index]);el.stop().animate({top:0-(self.current*height)+'px'},{duration:speed,easing:deck.options.transition,complete:function(){if(typeof(self.options.complete)==='function'){self.options.complete(self)}
if(typeof(callback)==='object'){if(typeof(callback.complete)==='function'){callback.complete(self)}}else if(typeof(callback)==='function'){callback(deck)}}})};var createVerticalNav=function(){var navParent=document.createElement('UL');navParent.className=self.classes.navContainer;navParent.style.position='absolute';navParent.style.zIndex=zIndex;navParent.style.listStyleType='none';for(var a=0;a<total;a++){var navLi=document.createElement('LI');navLi.className='nav_'+(a+1)+(a===0?' active':'');navLi.style.listStyleType='none';var navChild=document.createElement('A');if(elChildren[a].id){navChild.href="#"+elChildren[a].id}else{navChild.href="#"+(a+1)}
navChild.className='nav_'+(a+1);var navTitle="Nav "+(a+1);if(typeof(elNavTitles)!=='undefined'){navTitle=elNavTitles.eq(a).html()}
navChild.innerHTML=navTitle;navLi.appendChild(navChild);navParent.appendChild(navLi)}
var arrow=document.createElement('LI');arrow.className=self.classes.arrow;arrow.style.top=0;arrow.appendChild(document.createTextNode(' '));navParent.appendChild(arrow);parentSlide.append(navParent);self.navChildren=parentSlide.find('.'+navParent.className+' li');parentSlide.find('.'+navParent.className+' li a').click(function(event){event.preventDefault();deck.pauseAutoPlay=!0;slide(this.className.match('nav_([0-9]+)')[1]-1)})};this.goTo=function(v,h,snap){v=Math.min(total-1,Math.max(0,v-1));h=Math.min(deck.slides.length-1,Math.max(0,v));$(deck.slides[h]).find('.'+this.classes.navContainer+' a:eq('+v+')').addClass(deck.classes.active).siblings().removeClass(deck.classes.active);slide(v,snap)};this.next=function(callback){slide(Math.min(total-1,self.current+1),undefined,callback)};this.prev=function(callback){slide(Math.max(0,self.current-1),undefined,callback)};this.snapTo=function(v,callback){slide(Math.max(0,Math.min(total-1,v)),!0,callback)};var initialize=function(){if(!parentSlide.find('.'+self.classes.navContainer).length){var spineOffset=(((deck.browser.msie!==!0)||deck.browser.msie9||deck.browser.msie10)?$(deck.spines[0]).outerHeight():$(deck.spines[0]).outerWidth());if(deck.options.hideSpines===!0){spineOffset=0}
el.css({position:'absolute',zIndex:zIndex-1,top:'0px',left:spineOffset,listStyleType:'none',padding:'0px',margin:'0px',width:elParent.innerWidth()-spineOffset,height:height*total});var slidePadding={top:parseInt(elChildren.css('padding-top'),10),right:parseInt(elChildren.css('padding-right'),10),bottom:parseInt(elChildren.css('padding-bottom'),10),left:parseInt(elChildren.css('padding-left'),10)};var slideBorder={top:parseInt(elChildren.css('border-top-width'),10),right:parseInt(elChildren.css('border-right-width'),10),bottom:parseInt(elChildren.css('border-bottom-width'),10),left:parseInt(elChildren.css('border-left-width'),10)};for(var k in slideBorder){if(isNaN(slideBorder[k])){slideBorder[k]=0}}
var slideHeight=height-slidePadding.top-slidePadding.bottom-slideBorder.top-slideBorder.bottom;var slideWidth=el.width()-slidePadding.right-slidePadding.left-slideBorder.right-slideBorder.left;elChildren.each(function(ind,e){$(e).css({listStyleType:'none',position:'absolute',top:ind*height,width:slideWidth,height:slideHeight}).addClass(self.classes.prefix+'_'+(ind+1))});$(elChildren.get(0)).addClass(deck.classes.active);elParent.css({overflow:'hidden'});createVerticalNav();if(typeof($.event.special.mousewheel)!=="undefined"){el.bind("mousewheel",function(event,mousewheeldelta){if(self.options.scroll!==!1){var delta=event.detail?event.detail:event.wheelDelta;if(typeof(delta)==='undefined'){delta=0-mousewheeldelta}
var internal=!1;if($(event.originalTarget).parents(self.deck).length){if($.inArray(event.originalTarget.nodeName.toLowerCase(),['input','select','option','textarea'])!==-1){internal=!0}}
if(internal!==!0){var firstSlide,lastSlide=!1;if(self.options.continueScrolling===!0){if((self.current+1)===1){firstSlide=!0}else if((self.current+1)===self.slides.length){lastSlide=!0}}
if(delta>0){event.preventDefault();deck.pauseAutoPlay=!0;if(lastSlide){deck.next();return!1}else{self.next()}}else{event.preventDefault();deck.pauseAutoPlay=!0;if(firstSlide){deck.prev();return!1}else{self.prev()}}}}})}}};if(height>0){initialize()}else{var startupTimer;startupTimer=setInterval(function(){el=$(el);elChildren=el.children();total=elChildren.length;parentSlide=el.parents('.slide');elParent=el.parent();height=parentSlide.innerHeight();if(height>0){clearInterval(startupTimer);initialize()}},20)}};var setupDimensions=function(){height=el.height();width=el.width();el.css('height',height+"px");spine_inner_width=0;spine_outer_width=0;if(self.options.hideSpines!==!0&&self.spines.length>0){spine_inner_width=$(self.spines[0]).height();spine_outer_width=$(self.spines[0]).outerHeight()}
slide_width=width;spine_half_width=Math.ceil(spine_inner_width/2)};var initialize=function(opts){if((self.browser.opera&&self.browser.version<"10.5")||self.browser.msie6||self.browser.firefox2||self.browser.firefox30){if(typeof(console)!=="undefined"){if(typeof(console.error)==="function"){console.error("This web browser is not supported by SlideDeck. Please view this page in a modern, CSS3 capable browser or a current version of Internet Explorer")}}
return!1}
if(typeof(opts)!=="undefined"){for(var key in opts){self.options[key]=opts[key]}}
if(self.spines.length<1){self.options.hideSpines=!0}
switch(self.browser._this){case "msie":case "msie7":case "msie8":case "msie9":case "msie10":switch(self.options.slideTransition){case "flip":case "flipHorizontal":self.options.slideTransition="fade";break}
break}
switch(self.options.slideTransition){case "flip":case "flipHorizontal":case "fade":case "stack":self.options.hideSpines=!0;break}
if(self.options.hideSpines===!0){self.options.activeCorner=!1}
self.current=Math.min(self.slides.length,Math.max(1,self.options.start));if(el.height()>0){setupDimensions();buildDeck()}else{var startupTimer;startupTimer=setTimeout(function(){setupDimensions();if(el.height()>0){clearInterval(startupTimer);setupDimensions();buildDeck()}},20)}};var loaded=function(func){var thisTimer;thisTimer=setInterval(function(){if(self.isLoaded===!0){clearInterval(thisTimer);func(self)}},20)};this.autoAdjustAfterLoad=function(func){if(self.slides.length>0){for(var i=0;i<self.slides.length;i++){if(i===self.current-1){autoAdjustHeight()}}}};this.reloadSlidedeck=function(func){buildDeck();if(self.slides.length>1){for(var i=0;i<self.slides.length;i++){if(i===self.current-1){autoAdjustHeight()}}}};this.loaded=function(func){loaded(func);return self};this.next=function(params){var nextSlide=Math.min(self.slides.length,(self.current+1));if(self.options.cycle===!0){if(self.current+1>self.slides.length){nextSlide=1}}
slide(nextSlide,params);if(self.options.progressBar==!0){animateTimeline()}
return self};this.prev=function(params){var prevSlide=Math.max(1,(self.current-1));if(self.options.cycle===!0){if(self.current-1<1){prevSlide=self.slides.length}}
slide(prevSlide,params);if(self.options.progressBar==!0){animateTimeline()}
return self};this.goTo=function(ind,params){self.pauseAutoPlay=!0;if(typeof(ind)==="string"){if(ind===":first"){ind=self.slides.filter(':first')}else if(ind===":last"){ind=self.slides.filter(':last')}else if(!ind.match(/^\#/)){ind="#"+ind}
var slideIndex=self.slides.index($(ind));if(slideIndex!==-1){ind=slideIndex+1}
else{return!1}}
slide(Math.min(self.slides.length,Math.max(1,ind)),params);return self};this.progressTo=function(ind,params){self.pauseAutoPlay=!0;self.updateControlTo(ind);self.goTo(ind,params);return self};this.updateControlTo=function(ind){self.controlTo=ind;updateControl();return self};this.disableSlide=function(ind){disableSlide(ind);return self};this.enableSlide=function(ind){enableSlide(ind);return self};this.setOption=function(opts,val){setOption(opts,val);return self};this.vertical=function(opts){var self=this;if(typeof(this.verticalSlides)==='undefined'){this.verticalSlides={};for(var i=0;i<this.slides.length;i++){var slideElem=$(this.slides[i]).find('.'+this.classes.vertical);var v={next:function(){return!1},prev:function(){return!1},goTo:function(){return!1}};if(slideElem.length){v=new VerticalSlide(slideElem,this,opts)}
this.verticalSlides[i]=v}}else{return this.verticalSlides[this.current-1]}};this.goToVertical=function(v,h){if(typeof(h)!=='undefined'){if(this.verticalSlides[h-1]!==!1){if(this.current===h){this.vertical().goTo(v)}else{this.verticalSlides[h-1].goTo(v,h,!0);this.goTo(h)}}}else{this.vertical().goTo(v)}};this.resetVertical=function(h,snapTo){if(typeof(snapTo)==='undefined'){snapTo=!0}
if(typeof(h)==='undefined'){h=this.current}
if(snapTo===!0){this.verticalSlides[h-1].snapTo(0)}else{this.verticalSlides[h-1].goTo(0)}};initialize(opts)};$.fn.slidedeck=function(opts){var returnArr=[];for(var i=0;i<this.length;i++){if(!this[i].slidedeck){this[i].slidedeck=new SlideDeck(this[i],opts)}
returnArr.push(this[i].slidedeck)}
return returnArr.length>1?returnArr:returnArr[0]}})(jQuery)
	
